name: Deploy Project RealTalk

on:
  push:
    branches: [ "main", "feat/#12" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Gradle
        run: ./gradlew bootjar

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/realtalk-backend:${{ github.sha }} .

      - name: Login to DockerHub
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/realtalk-backend:${{ github.sha }}

      - name: Deploy on NAS via SSH
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.NAS_HOST }}
          username: ${{ secrets.NAS_USER }}
          password: ${{ secrets.NAS_PASSWORD }}
          script: |
            cd realtalk-project-backend
            git pull origin feat/#12
          
            docker network inspect prod_server || docker network create prod_server

            if ! docker ps --format '{{.Names}}' | grep -qw nginx; then
            docker-compose up -d nginx
            fi
            if ! docker ps --format '{{.Names}}' | grep -qw redis; then
            docker-compose up -d redis
            fi

            docker pull ${{ secrets.DOCKER_USERNAME }}/realtalk-backend:${{ github.sha }}
            docker stop spring-app || true
            docker rm spring-app || true
            docker run -d --name spring-app \
              --network prod_server \
              -p 8080:8080 \
              -e MYSQL_HOST=${{ secrets.MYSQL_HOST }} \
              -e MYSQL_PORT=${{ secrets.MYSQL_PORT }} \
              -e MYSQL_DATABASE=${{ secrets.MYSQL_DATABASE }} \
              -e MYSQL_USERNAME=${{ secrets.MYSQL_USERNAME }} \
              -e MYSQL_PASSWORD=${{ secrets.MYSQL_PASSWORD }} \
              -e REDIS_HOST=${{ secrets.REDIS_HOST }} \
              -e REDIS_PORT=${{ secrets.REDIS_PORT }} \
              -e ANTHROPIC_API_KEY=${{ secrets.ANTHROPIC_API_KEY }} \
              -e KAKAO_CLIENT_ID=${{ secrets.KAKAO_CLIENT_ID }} \
              -e KAKAO_CLIENT_SECRET=${{ secrets.KAKAO_CLIENT_SECRET }} \
              -e GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }} \
              -e GOOGLE_CLIENT_SECRET=${{ secrets.GOOGLE_CLIENT_SECRET }} \
              -e GOOGLE_CLIENT_NAME=${{ secrets.GOOGLE_CLIENT_NAME }} \
              -e JWT_SECRET=${{ secrets.JWT_SECRET }} \
              ${{ secrets.DOCKER_USERNAME }}/realtalk-backend:${{ github.sha }}