name: Deploy Project RealTalk

on:
  push:
    branches: [ "main", "chore/#18" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Gradle
        run: ./gradlew bootjar

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/realtalk-backend:${{ github.sha }} .

      - name: Login to DockerHub
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/realtalk-backend:${{ github.sha }}

      - name: Deploy on NAS via SSH
        uses: appleboy/ssh-action@v1
        env:
          MYSQL_HOST=${{ secrets.MYSQL_HOST }}
          MYSQL_PORT=${{ secrets.MYSQL_PORT }}
          MYSQL_DATABASE=${{ secrets.MYSQL_DATABASE }}
          MYSQL_USERNAME=${{ secrets.MYSQL_USERNAME }}
          MYSQL_PASSWORD=${{ secrets.MYSQL_PASSWORD }}
          REDIS_HOST=${{ secrets.REDIS_HOST }}
          REDIS_PORT=${{ secrets.REDIS_PORT }}
          ANTHROPIC_API_KEY=${{ secrets.ANTHROPIC_API_KEY }}
          KAKAO_CLIENT_ID=${{ secrets.KAKAO_CLIENT_ID }}
          KAKAO_CLIENT_SECRET=${{ secrets.KAKAO_CLIENT_SECRET }}
          GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }}
          GOOGLE_CLIENT_SECRET=${{ secrets.GOOGLE_CLIENT_SECRET }}
          GOOGLE_CLIENT_NAME=${{ secrets.GOOGLE_CLIENT_NAME }}
          JWT_SECRET=${{ secrets.JWT_SECRET }}
          BASE_URL=${{ secrets.BASE_URL }}
          FRONTEND_URL=${{ secrets.FRONTEND_URL }}
          DOCKER_USERNAME=${{ secrets.DOCKER_USERNAME }}
          GITHUB_SHA=${{ github.sha }}
        with:
          host: ${{ secrets.NAS_HOST }}
          username: ${{ secrets.NAS_USER }}
          password: ${{ secrets.NAS_PASSWORD }}
          envs: DOCKER_USERNAME,GITHUB_SHA,MYSQL_HOST,MYSQL_PORT,MYSQL_DATABASE,MYSQL_USERNAME,MYSQL_PASSWORD,REDIS_HOST,REDIS_PORT
          script: |
            cd realtalk-project-backend
            git pull origin chore/#18
            
            chmod +x deploy/deploy-single.sh
            ./deploy/deploy-single.sh
            
            # chmod +x deploy/deploy-bluegreen.sh
            # ./deploy/deploy-bluegreen.sh